import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          light: "var(--color-primary-light)",
          lighter: "var(--color-primary-lighter)",
          dark: "var(--color-primary-dark)",
          foreground: "var(--color-primary-foreground)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          hover: "var(--color-accent-hover)",
          light: "var(--color-accent-light)",
        },
        success: {
          DEFAULT: "var(--color-success)",
          light: "var(--color-success-light)",
          dark: "var(--color-success-dark)",
          foreground: "var(--color-success-foreground)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          light: "var(--color-warning-light)",
          dark: "var(--color-warning-dark)",
          foreground: "var(--color-warning-foreground)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          light: "var(--color-error-light)",
          dark: "var(--color-error-dark)",
          foreground: "var(--color-error-foreground)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          light: "var(--color-info-light)",
          dark: "var(--color-info-dark)",
          foreground: "var(--color-info-foreground)",
        },
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
        },
        bg: {
          page: "var(--color-bg-page)",
          card: "var(--color-bg-card)",
          hover: "var(--color-bg-hover)",
          active: "var(--color-bg-active)",
          sidebar: "var(--color-bg-sidebar)",
          "sidebar-active": "var(--color-bg-sidebar-active)",
          overlay: "var(--color-bg-overlay)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          disabled: "var(--color-text-disabled)",
          inverse: "var(--color-text-inverse)",
          link: "var(--color-text-link)",
          "link-hover": "var(--color-text-link-hover)",
        },
        border: {
          DEFAULT: "var(--color-border-default)",
          strong: "var(--color-border-strong)",
          focus: "var(--color-border-focus)",
          subtle: "var(--color-border-subtle)",
        },
        grade: {
          a: "var(--color-grade-a)",
          b: "var(--color-grade-b)",
          c: "var(--color-grade-c)",
          s: "var(--color-grade-s)",
        },
        stage: {
          need: "var(--color-stage-need)",
          sample: "var(--color-stage-sample)",
          quote: "var(--color-stage-quote)",
          negotiate: "var(--color-stage-negotiate)",
          won: "var(--color-stage-won)",
          lost: "var(--color-stage-lost)",
        },
      },
      fontFamily: {
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        xs: ["var(--font-size-xs)", "var(--line-height-normal)"],
        sm: ["var(--font-size-sm)", "var(--line-height-normal)"],
        base: ["var(--font-size-base)", "var(--line-height-normal)"],
        lg: ["var(--font-size-lg)", "var(--line-height-normal)"],
        xl: ["var(--font-size-xl)", "var(--line-height-tight)"],
        "2xl": ["var(--font-size-2xl)", "var(--line-height-tight)"],
        "3xl": ["var(--font-size-3xl)", "var(--line-height-tight)"],
        "4xl": ["var(--font-size-4xl)", "var(--line-height-tight)"],
      },
      spacing: {
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        8: "var(--spacing-8)",
        10: "var(--spacing-10)",
        12: "var(--spacing-12)",
        16: "var(--spacing-16)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      zIndex: {
        base: "var(--z-index-base)",
        dropdown: "var(--z-index-dropdown)",
        sticky: "var(--z-index-sticky)",
        floating: "var(--z-index-floating)",
        overlay: "var(--z-index-overlay)",
        modal: "var(--z-index-modal)",
        toast: "var(--z-index-toast)",
      },
      transitionDuration: {
        instant: "var(--motion-duration-instant)",
        fast: "var(--motion-duration-fast)",
        normal: "var(--motion-duration-normal)",
        slow: "var(--motion-duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-easing-standard)",
        decelerate: "var(--motion-easing-decelerate)",
        accelerate: "var(--motion-easing-accelerate)",
      },
    },
  },
  plugins: [],
};

export default config;
